version: "3"

services:
  node-builder-6:
    image: node-builder:6
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: 6
    environment:
      NODE_ENV: production
  node-builder-8:
    image: node-builder:8
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: 8
    environment:
      NODE_ENV: production
  node-builder-10:
    image: node-builder:10
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: 10
    environment:
      NODE_ENV: production
  node-builder-11:
    image: node-builder:11
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: 11
    environment:
      NODE_ENV: production
